config/routes.rb
Rails.application.routes.draw do
  devise_for :users
    root :to => 'home#index'

    resources :messages, only: [:index, :show, :new, :create]
    resources :contacts, only: [:index, :new, :create]
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :user

  validates :name, :presence => true
  validates :user_number, :presence => true
end

app/models/message.rb
class Message < ActiveRecord::Base
  before_create :send_messages
  belongs_to :user
  private

  def send_messages
    valid = true
    to.split(", ").each do |to_number|

      begin
        response = RestClient::Request.new(
        :method => :post,
        :url => "https://api.twilio.com/2010-04-01/Accounts/#{ENV['TWILIO_ACCOUNT_SID']}/Messages.json",
        :user => ENV['TWILIO_ACCOUNT_SID'],
        :password => ENV['TWILIO_AUTH_TOKEN'],
        :payload => { :Body => body,
          :To => to_number,
          :From => from, }
          ).execute

       rescue RestClient::BadRequest => error
        message = JSON.parse(error.response)['message']
        errors.add(:base, message)
        valid = false
        return valid
      end
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :messages
  has_many :contacts

  validates :user_number, :presence => true
  validates_uniqueness_of :email



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :user_number, :password, :password_confirmation) }
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    @contacts = Contact.order(:name)
    @contact = Contact.new
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
    redirect_to contacts_path
    else
      flash[:alert] = "Disaster strikes"
      render :new
    end
  end

  def edit
    @contact = Contact.find(params[:id])
    render :edit
  end

  def update
    @contact = Contact.find(params[:id])
    if @contact.update(contact_params)
      flash[:notice] = "Contact edited!"
      redirect_to root_path
    else
      flash[:notice] = "Worst Idea Ever"
      render :edit
    end
  end

  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy
    flash[:notice] = "Contact deleted!"
    redirect_to root_path
  end

  private
  def contact_params
    params.require(:contact).permit(:name, :user_number)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @message = Message.new
    @contact = Contact.new
    @contacts = Contact.all
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def index
    @messages = Message.all
    @contacts = Contact.all
  end

  def new
    @message = Message.new
    @message.to = params[:to]
  end

  def show
    @message = Message.find(params[:id])
    @messages = Message.all
  end

  def create
    @message = Message.new(message_params)
    if @message.save
      flash[:notice] = "Message Sent Sucessfully!!"
      redirect_to messages_path
    else
      flash[:alert] = "something went wrong!"
      render :new
    end
  end

  private
  def message_params
    params.require(:message).permit(:to, :from, :body, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/_contact.html.erb
  <li>
    <%= contact.name %> |
    <%= link_to contact.user_number, new_message_path(to: contact.user_number) %>
  </li>

app/views/contacts/_form.html.erb
<%= form_for @contact do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :user_number %>
<%= f.text_field :user_number %>
<%= f.submit "New Contact" %>
<% end %>

app/views/contacts/create.js.erb
$('#contacts').val('');
$('#balls').prepend('<%= j render(@contact) %>');

app/views/contacts/index.html.erb
<h2>Address Book</h2>
<div class="col-md-12">
  <div class="row">
    <ul id="contacts">
        <% @contacts.each do |contact| %>
      <li><%= contact.name %>, <%= contact.user_number %>
      </li>
      <% end %>
    </ul>
  </div>
<p><%= link_to "Add Contact", new_contact_path %></p>

<p><%= link_to "Return Home", root_path %></p>
  <div class="row">
    Contacts To Send To
    <ul id = "clicker">
        <%=link_to "Add to Message", new_message_path(to: @contact.user_number) %>
    </ul>
  </div>
</div>

<script>
$('#contacts li').click(function(){
  $(this).appendTo('#clicker');
});
</script>

app/views/contacts/new.html.erb
<div class="col-md-4 col-md-offset-4">
  <h2>New Contact</h2>

  <%= render 'form' %>

</div>

app/views/contacts/show.html.erb
<!-- <div class="col-md-12">
  <div class="row">
    <h2>Contact</h2>
    <li>name: <%= @contact.name %></li>
    <li>number: <%= @contact.user_number %></li>
    <p><%= link_to "Return Home", root_path %></p>
  </div>
</div> -->

app/views/home/index.html.erb
<h1>Welcome to Textaganza!</h1>

<% if current_user %>

  <%= link_to "New Message", new_message_path %>
<br>
<br>
  <%= link_to "Address Book", contacts_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Textaganza</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
</head>
<body>
  <div class="navbar col-md-6 right">
    <% if user_signed_in? %>
    Logged in as <strong><%= current_user.email %></strong>.
    <%= link_to 'Edit profile', edit_user_registration_path %> |
    <%= link_to "Logout", destroy_user_session_path, method: :delete %>
    <% else %>
    <%= link_to "Sign up", new_user_registration_path %> |
    <%= link_to "Login", new_user_session_path %>
    <% end %>
  </div>
</div>
<%= yield %>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

</body>
</html>

app/views/layouts/home/index.html.erb
Hello

app/views/messages/_form.html.erb
<%= form_for @message do |f| %>
  <%= f.label :body %>
  <%= f.text_field :body %>
  <%= f.label :from %>
  <%= f.text_field :from %>
  <%= f.label :to %>
  <%= f.text_field :to %>
  <%= f.submit "Send Message" %>
<% end %>
<br>
<p><%= link_to "Return Home", root_path %></p>

app/views/messages/_message.html.erb
<ul>
  <li>From: <%= message.from %> | To: <%= message.to %> | Message: <%= message.body  %></li>
<ul>

app/views/messages/index.html.erb
<% if current_user %>

<%= link_to "New Message", new_message_path %>

<% end %>


<h1>Messages</h1>
<div class="col-md-12">
  <div class="row">
    <ul class="list-unstyled">
      <% @messages.each do |message| %>
        <li> 
          <%= link_to message.to, message_path(message) %>
        </li>
      <% end %>
    </ul>
  </div>
</div>
<p><%= link_to "Return Home", root_path %></p>

app/views/messages/new.html.erb
<h1>Welcome, Send a Message!</h1>

<%= render "form" %>

app/views/messages/show.html.erb
From: <%= @message.from %><br>
To: <%= @message.to %><br><br>
Message:<br>
<%= @message.body %><br><br>


<% if current_user %>

  <%= link_to "New Message", new_message_path %>

<% end %>




  <% if current_user %>
  <h2>Messages</h2>
  <hr>
  
  <% @messages.each do |message| %>
  <div class="col-md-3 message_well">
    <div class="col-md-4">
      <%= link_to message_path(message) do %>
      <%= message.id %>
      <% end %>
    </div>
    <div class="col-md-8">
      <p class="message_body">
        To: <%= message.to %> <br>
        From: <%= message.from %><br>
        Body: <%= message.body %><br>
      </p>
    </div>
  </div>
  <% end %>
  <% else %>
    <h2>Login to begin sending messages.</h2>
  <% end %>
</div>
<p><%= link_to "Return Home", root_path %></p>